name: Stage the app

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: dans002-azure-ttt
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_WEBAPP_NAME: dans002-ttt-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
